# Generated by Django 4.0 on 2023-06-15 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_alter_role_role_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Message', models.CharField(blank=True, max_length=1000, null=True)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_created_by', to='account.user')),
            ],
        ),
    ]
