# Generated by Django 4.0 on 2023-06-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='changes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
