# Generated by Django 4.0 on 2023-06-16 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_changes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='changes',
            new_name='Changes',
        ),
    ]
