# Generated by Django 4.0 on 2023-06-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_rename_changes_message_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
