# Generated by Django 4.2.1 on 2023-06-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_status',
            field=models.CharField(choices=[(2, 'passive'), (1, 'active')], default=1, max_length=20),
        ),
    ]
