# Generated by Django 4.0 on 2023-06-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_role_role_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_status',
            field=models.CharField(choices=[(2, 'passive'), (1, 'active')], default=1, max_length=20),
        ),
    ]
