# Generated by Django 4.0 on 2023-05-25 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0016_alter_role_role_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('STK_NO', models.IntegerField()),
                ('SIZE', models.IntegerField()),
                ('SHAPE', models.CharField(max_length=100)),
                ('COLOR', models.CharField(max_length=100)),
                ('CLARITY', models.CharField(max_length=100)),
                ('POL', models.CharField(max_length=100)),
                ('SYM', models.CharField(max_length=100)),
                ('CUT', models.CharField(max_length=100)),
                ('FLO_COL', models.CharField(max_length=100)),
                ('MESUREMNT', models.CharField(max_length=100)),
                ('DEPTH', models.FloatField()),
                ('TABLE', models.FloatField()),
                ('GIA_NO', models.CharField(max_length=100)),
                ('REMARK', models.CharField(max_length=500)),
                ('PHOTO', models.ImageField(upload_to='')),
                ('VIDEO', models.CharField(max_length=100)),
                ('PRICE', models.FloatField()),
                ('STK_ID', models.CharField(max_length=100)),
                ('CRT', models.FloatField()),
                ('PURITY', models.CharField(max_length=100)),
                ('DESCRIPTION', models.TextField(blank=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Scan_Id', models.IntegerField()),
                ('CretedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_created_by', to='account.user')),
                ('UpdatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_updated_by', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('Log_Id', models.AutoField(primary_key=True, serialize=False)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('Log_message', models.TextField()),
                ('Notified', models.BooleanField(default=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
