# Generated by Django 4.2.1 on 2023-06-10 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('company', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('STK_ID', models.CharField(max_length=100, unique=True)),
                ('SHAPE', models.CharField(blank=True, max_length=100, null=True)),
                ('COLOR', models.CharField(blank=True, max_length=100, null=True)),
                ('CLARITY', models.CharField(blank=True, max_length=100, null=True)),
                ('POL', models.CharField(blank=True, max_length=100, null=True)),
                ('SYM', models.CharField(blank=True, max_length=100, null=True)),
                ('CUT', models.CharField(blank=True, max_length=100, null=True)),
                ('FLO_COL', models.CharField(blank=True, max_length=100, null=True)),
                ('MESUREMNT', models.CharField(blank=True, max_length=100, null=True)),
                ('DEPTH', models.FloatField(blank=True, null=True)),
                ('TABLE', models.FloatField(blank=True, null=True)),
                ('GIA_NO', models.CharField(blank=True, max_length=100, null=True)),
                ('REMARK', models.CharField(blank=True, max_length=500, null=True)),
                ('PRICE', models.FloatField()),
                ('CRT', models.FloatField()),
                ('DESCRIPTION', models.TextField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Scan_Id', models.BigIntegerField(blank=True, null=True)),
                ('MemoMade', models.BooleanField(default=False)),
                ('InvoiceMade', models.BooleanField(default=False)),
                ('IsHide', models.BooleanField(default=False)),
                ('CretedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_created_by', to=settings.AUTH_USER_MODEL)),
                ('UpdatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id_invoice', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('DeletedOn', models.DateTimeField(blank=True, null=True)),
                ('CretedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_created_by', to=settings.AUTH_USER_MODEL)),
                ('DeletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.client')),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id_memo', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('DeletedOn', models.DateTimeField(blank=True, null=True)),
                ('CretedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memo_created_by', to=settings.AUTH_USER_MODEL)),
                ('DeletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.client')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/videos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('id_inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='MemoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('weight', models.FloatField()),
                ('rate', models.FloatField()),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.memo')),
                ('stk_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', to_field='STK_ID')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('pcs', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField()),
                ('cfr', models.FloatField()),
                ('total', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.invoice')),
                ('stk_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', to_field='STK_ID')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('Log_Id', models.AutoField(primary_key=True, serialize=False)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('Log_message', models.TextField()),
                ('Notified', models.BooleanField(default=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
