# Generated by Django 4.0 on 2023-06-01 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id_client', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('company', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='memo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='company',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='name',
        ),
        migrations.AddField(
            model_name='memo',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.client'),
            preserve_default=False,
        ),
    ]
