# Generated by Django 4.0 on 2023-05-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='PHOTO',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='VIDEO',
            field=models.URLField(),
        ),
    ]
