# Generated by Django 4.0 on 2023-06-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
