# Generated by Django 4.0 on 2023-05-25 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventory_photo_alter_inventory_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='PHOTO',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
