# Generated by Django 4.0 on 2023-06-09 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_role_role_status'),
        ('inventory', '0002_alter_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id_invoice', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('DeletedOn', models.DateTimeField(blank=True, null=True)),
                ('CretedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_created_by', to='account.user')),
                ('DeletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_deleted_by', to='account.user')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.client')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('pcs', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField()),
                ('cfr', models.FloatField()),
                ('total', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.invoice')),
                ('stk_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', to_field='STK_ID')),
            ],
        ),
    ]
