# Generated by Django 4.0 on 2023-06-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_depth_alter_inventory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
