# Generated by Django 4.0 on 2023-05-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='PHOTO',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='VIDEO',
            field=models.CharField(max_length=1000),
        ),
    ]
