# Generated by Django 4.0 on 2023-06-01 06:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_alter_role_role_status'),
        ('inventory', '0003_memo_is_deleted_alter_memo_stk_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memo',
            name='CretedBy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='memo_created_by', to='account.user'),
            preserve_default=False,
        ),
    ]
