# Generated by Django 4.0 on 2023-06-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_invoice_invoicedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='InvoiceMade',
            field=models.BooleanField(default=False),
        ),
    ]
