# Generated by Django 4.0 on 2023-06-01 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_memo_createdon_memo_cretedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='stk_no',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='weight',
        ),
        migrations.CreateModel(
            name='MemoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('weight', models.FloatField()),
                ('rate', models.FloatField()),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.memo')),
                ('stk_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', to_field='STK_ID')),
            ],
        ),
    ]
