# Generated by Django 4.0 on 2023-06-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory_invoicemade'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='IsHide',
            field=models.BooleanField(default=False),
        ),
    ]
