# Generated by Django 4.0 on 2023-06-20 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_role_role_status'),
        ('inventory', '0005_inventory_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyData',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Submitted', models.BooleanField(default=False)),
                ('stk_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', to_field='STK_ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tally',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=500, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('DeletedOn', models.DateTimeField(blank=True, null=True)),
                ('CretedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_created_by', to='account.user')),
                ('DeletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tally_deleted_by', to='account.user')),
            ],
        ),
    ]
