# Generated by Django 4.0 on 2023-06-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_memo_desc_remove_memo_rate_remove_memo_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='MemoMade',
            field=models.BooleanField(default=False),
        ),
    ]
