# Generated by Django 4.0 on 2023-05-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_updatedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Scan_Id',
            field=models.IntegerField(blank=True),
        ),
    ]
