# Generated by Django 4.0 on 2023-06-10 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_ishide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='IsSold',
        ),
    ]
