# Generated by Django 4.0 on 2023-06-03 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_alter_role_role_status'),
        ('inventory', '0006_inventory_memomade'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='DeletedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo_deleted_by', to='account.user'),
        ),
        migrations.AddField(
            model_name='memo',
            name='DeletedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
