# Generated by Django 4.0 on 2023-06-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_memo_deletedby_memo_deletedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='IsSold',
            field=models.BooleanField(default=False),
        ),
    ]
