# Generated by Django 4.0 on 2023-05-27 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_role_role_status'),
        ('inventory', '0007_alter_inventory_scan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='UpdatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_updated_by', to='account.user'),
        ),
    ]
