# Generated by Django 4.0 on 2023-06-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_submitted_tallydata_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally',
            name='Isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
