# Generated by Django 4.0 on 2023-05-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventory_updatedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/videos/')),
                ('image', models.ImageField(upload_to='uploads/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='PHOTO',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='VIDEO',
        ),
    ]
