# Generated by Django 4.0 on 2023-06-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_tally_isdeleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
