# Generated by Django 4.0 on 2023-05-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_video_remove_inventory_photo_remove_inventory_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
    ]
