# Generated by Django 4.0 on 2023-05-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_video_id_inv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
