# Generated by Django 4.2.1 on 2023-05-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0015_alter_video_file_alter_video_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="link",
            field=models.CharField(blank=True, null=True),
        ),
    ]
