# Generated by Django 4.0 on 2023-06-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jewellery',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('Price', models.FloatField()),
                ('Color', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='uploads/jewellery/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Parcels',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Stk_Id', models.CharField(max_length=100, unique=True)),
                ('Crt', models.FloatField()),
                ('Clarity', models.CharField(blank=True, max_length=100, null=True)),
                ('Desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('Price', models.FloatField()),
                ('Color', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='uploads/parcels/images/')),
                ('Shape', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
