# Generated by Django 4.0 on 2023-06-12 10:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_groups_alter_user_user_permissions'),
        ('parcels_jewellery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewellery',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jewellery',
            name='CretedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jewellery_created_by', to='account.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jewellery',
            name='UpdatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jewellery_updated_by', to='account.user'),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='UpdatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parcels',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcels',
            name='CretedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parcels_created_by', to='account.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcels',
            name='UpdatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels_updated_by', to='account.user'),
        ),
        migrations.AddField(
            model_name='parcels',
            name='UpdatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
