# Generated by Django 4.0 on 2023-06-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels_jewellery', '0002_jewellery_createdon_jewellery_cretedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewellery',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='parcels',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
