# Generated by Django 4.0 on 2023-06-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels_jewellery', '0004_alter_jewellery_image_alter_parcels_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewellery',
            name='Isdeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcels',
            name='Isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
