# Generated by Django 4.0 on 2023-06-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels_jewellery', '0005_jewellery_isdeleted_parcels_isdeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewellery',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/jewellery/'),
        ),
        migrations.AlterField(
            model_name='parcels',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/parcels/'),
        ),
    ]
