# Generated by Django 4.0 on 2023-06-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels_jewellery', '0006_alter_jewellery_image_alter_parcels_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
