# Generated by Django 4.0 on 2023-06-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels_jewellery', '0008_jewellery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
