# Generated by Django 4.0 on 2023-06-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels_jewellery', '0009_alter_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewellery',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='jewellery/'),
        ),
        migrations.AlterField(
            model_name='parcels',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='parcels/'),
        ),
    ]
